import * as Viewer from '../viewer.js';

import { SFAMapSceneDesc, SwapcircleSceneDesc, AncientMapSceneDesc, EarlydupMapSceneDesc, EarlyfearMapSceneDesc, EarlyDFPMapSceneDesc, Early1MapSceneDesc, Early2MapSceneDesc, Early3MapSceneDesc, Early4MapSceneDesc, } from './maps.js';
import { SFAWorldSceneDesc } from './world.js';
import { SFAModelExhibitSceneDesc } from './modelexhibit.js';
import { ModelVersion } from './modelloader.js';
import { EARLYFEAR } from './blocks.js';

export interface GameInfo {
    pathBase: string;
    subdirs: {[key: number]: string};
}
console.error("🔥 SFA SCENE GROUP LOADED 🔥");

export const SFA_GAME_INFO: GameInfo = {
    pathBase: 'StarFoxAdventures',
    subdirs: {
        0: 'animtest',
        1: 'animtest',
        2: 'animtest',
        3: 'arwing',
        4: 'dragrock',
        5: 'animtest',
        6: 'dfptop',
        7: 'volcano',
        8: 'animtest',
        9: 'mazecave',
        10: 'dragrockbot',
        11: 'dfalls',
        12: 'swaphol',
        13: 'shipbattle',
        14: 'nwastes',
        15: 'warlock',
        16: 'shop',
        17: 'animtest',
        18: 'crfort',
        19: 'swapholbot',
        20: 'wallcity',
        21: 'lightfoot',
        22: 'cloudtreasure',
        23: 'animtest',
        24: 'clouddungeon',
        25: 'mmpass',
        26: 'darkicemines',
        27: 'animtest',
        28: 'desert',
        29: 'animtest',
        30: 'icemountain',
        31: 'animtest',
        32: 'animtest',
        33: 'animtest',
        34: 'darkicemines2',
        35: 'bossgaldon',
        36: 'animtest',
        37: 'insidegal',
        38: 'magiccave',
        39: 'dfshrine',
        40: 'mmshrine',
        41: 'ecshrine',
        42: 'gpshrine',
        43: 'dbshrine',
        44: 'nwshrine',
        45: 'worldmap',
        46: 'animtest',
        47: 'capeclaw',
        48: 'dbay',
        49: 'animtest',
        50: 'cloudrace',
        51: 'bossdrakor',
        52: 'animtest',
        53: 'bosstrex',
        54: 'linkb',
        55: 'cloudjoin',
        56: 'arwingtoplanet',
        57: 'arwingdarkice',
        58: 'arwingcloud',
        59: 'arwingcity',
        60: 'arwingdragon',
        61: 'gamefront',
        62: 'linklevel',
        63: 'greatfox',
        64: 'linka',
        65: 'linkc',
        66: 'linkd',
        67: 'linke',
        68: 'linkf',
        69: 'linkg',
        70: 'linkh',
        71: 'linkj',
        72: 'linki',
    },
};

export const SFADEMO_GAME_INFO: GameInfo = {
    pathBase: 'StarFoxAdventuresDemo',
    subdirs: {
        0: 'animtest',
        1: 'animtest',
        2: 'animtest',
        3: 'arwing',
        4: 'dragrock',
        5: 'animtest',
        6: 'dfptop',
        7: 'volcano',
        8: 'animtest',
        9: 'mazecave', // 9: 'animtest',
        10: 'dragrockbot',
        11: 'dfalls',
        12: 'swaphol',
        13: 'shipbattle', // 13: 'animtest',
        14: 'nwastes',
        15: 'warlock',
        16: 'shop',
        17: 'animtest',
        18: 'crfort',
        19: 'swapholbot',
        20: 'wallcity',
        21: 'lightfoot',
        22: 'cloudtreasure',
        23: 'animtest',
        24: 'clouddungeon',
        25: 'mmpass',
        26: 'darkicemines',
        27: 'dfptop', // 27: 'animtest',
        28: 'desert',
        29: 'frontend', // 29: 'animtest',
        30: 'icemountain',
        31: 'mmshrine', // 31: 'animtest',
        32: 'animtest',
        33: 'animtest',
        34: 'darkicemines2',
        35: 'bossgaldon',
        36: 'animtest',
        37: 'insidegal',
        38: 'magiccave',
        39: 'dfshrine',
        40: 'mmshrine',
        41: 'ecshrine',
        42: 'gpshrine',
        43: 'dbshrine',
        44: 'nwshrine',
        45: 'worldmap',
        46: 'animtest',
        47: 'capeclaw',
        48: 'dbay',
        49: 'animtest',
        50: 'cloudrace',
        51: 'bossdrakor',
        52: 'animtest',
        53: 'bosstrex',
        54: 'linkb', // 54: 'animtest',
        // The following entries are missing from the demo executable.
        57: 'arwingdarkice',
        58: 'arwingcloud',
        59: 'arwingcity',
        60: 'arwingdragon',
        61: 'gamefront',
        62: 'linklevel',
        63: 'greatfox',
        64: 'linka',
        65: 'linkc',
        66: 'linkd',
        67: 'linke',
        68: 'linkf',
        69: 'linkg',
        70: 'linkh',
        71: 'linkj',
        72: 'linki',
        73: 'swapcircle',
        74: 'Copy of swaphol',
 
    }
};

const ANCIENT_DP_GAME_INFO: GameInfo = {
    pathBase: 'StarFoxAdventuresDemo',
    subdirs: [], // N/A
};

const sceneDescs = [
    'StarFox Adventures Maps - Oldest to Newest',
    "Model Viewer",
new SFAModelExhibitSceneDesc('modelexhibit', 'Model + Animation Viewer (Final)', ModelVersion.Final),
new SFAModelExhibitSceneDesc('modelexhibit', 'Model + Animation Viewer (Kiosk)', ModelVersion.Final, SFADEMO_GAME_INFO),
new SFAModelExhibitSceneDesc('betamodelexhibit', 'Early 2001 Model Viewer (in progress)', ModelVersion.Beta, SFADEMO_GAME_INFO),
new SFAModelExhibitSceneDesc('demomodelexhibit', 'Mid 2001 Viewer (in progress)', ModelVersion.Demo, SFADEMO_GAME_INFO),

'Very Early 2001 Maps',
 new SwapcircleSceneDesc(22, 'betaswapcircle', 'Very Early 2001: Swapstone Circle (T)', SFADEMO_GAME_INFO),
new EarlyDFPMapSceneDesc(50, 'demo50', 'Very Early 2001: Desert Force Point - Top (T)', SFADEMO_GAME_INFO),
new EarlyfearMapSceneDesc(33, 'demo33', 'Very Early 2001: Test of Fear (T)', SFADEMO_GAME_INFO),
 new EarlyDFPMapSceneDesc(23, 'demo23', 'Very Early 2001: Ice Mountain 2', SFADEMO_GAME_INFO),


    'Early 2001 Maps',
    new AncientMapSceneDesc('ancient0', "Ancient Willow Grove (T)", ANCIENT_DP_GAME_INFO, 0),
    new AncientMapSceneDesc('ancient1', "Ancient Dragon Rock", ANCIENT_DP_GAME_INFO, 1),
    new AncientMapSceneDesc('ancient2', "Ancient Dragon Rock Bottom", ANCIENT_DP_GAME_INFO, 2),
    new AncientMapSceneDesc('ancient3', "Ancient ThornTail Hollow (T)", ANCIENT_DP_GAME_INFO, 3),
    new AncientMapSceneDesc('ancient4', "Ancient Northern Wastes (T)", ANCIENT_DP_GAME_INFO, 4),
    new AncientMapSceneDesc('ancient5', "Ancient Warlock Mountain (T)", ANCIENT_DP_GAME_INFO, 5),
    new AncientMapSceneDesc('ancient6', "Ancient Shop (T)", ANCIENT_DP_GAME_INFO, 6),
    new AncientMapSceneDesc('ancient7', "Ancient CloudRunner Fortress (T)", ANCIENT_DP_GAME_INFO, 7),
    new AncientMapSceneDesc('ancient9', "Ancient Ice Mountain Track 1", ANCIENT_DP_GAME_INFO, 9),
    new AncientMapSceneDesc('ancient10', "Ancient Ice Mountain Track 2", ANCIENT_DP_GAME_INFO, 10),
    new AncientMapSceneDesc('ancient11', "Ancient Ice Mountain Track 3", ANCIENT_DP_GAME_INFO, 11),
    new AncientMapSceneDesc('ancient8', "Ancient DarkIce Mines", ANCIENT_DP_GAME_INFO, 8),
    new AncientMapSceneDesc('ancient12', "Ancient DarkIce Mines 2", ANCIENT_DP_GAME_INFO, 12),
    new AncientMapSceneDesc('ancient13', "Ancient DarkIce Mines Boss Room", ANCIENT_DP_GAME_INFO, 13),
    new AncientMapSceneDesc('ancient14', "Ancient CloudRunner Fortress Race (T)", ANCIENT_DP_GAME_INFO, 14),
    new AncientMapSceneDesc('ancient15', "Ancient Boss T-rex", ANCIENT_DP_GAME_INFO, 15),

    'Early/Mid 2001 Maps',
    new Early1MapSceneDesc(26, 'demo26', 'Mid 2001: Animtest', SFADEMO_GAME_INFO),
    new Early1MapSceneDesc(18, 'demo18', 'Mid 2001: Moon Mountain Pass (T)', SFADEMO_GAME_INFO),
    new Early1MapSceneDesc(7, 'demo7', 'Mid 2001: ThornTail Hollow (T)', SFADEMO_GAME_INFO),
    new EarlydupMapSceneDesc(7, 'demo7', 'Mid 2001: ThornTail Hollow (Copy of Swaphol map) (T)', SFADEMO_GAME_INFO),
    new Early1MapSceneDesc(8, 'demo8', 'Mid 2001: ThornTail Hollow Underground (T)', SFADEMO_GAME_INFO),
    new Early1MapSceneDesc(64, 'demo64', 'Mid 2001: LinkLevel (Thorntail to Lightfoot) (T)', SFADEMO_GAME_INFO),
    new Early1MapSceneDesc(51, 'demo51', 'Mid 2001: Shop (T)', SFADEMO_GAME_INFO),
    new Early1MapSceneDesc(54, 'demo54', 'Mid 2001: Magic Cave (T)', SFADEMO_GAME_INFO),
    new Early1MapSceneDesc(29, 'demo29', 'Mid 2001: Cape Claw (T)', SFADEMO_GAME_INFO),
    new Early1MapSceneDesc(14, 'demo14', 'Mid 2001: LightFoot Village (T)', SFADEMO_GAME_INFO),
    new Early1MapSceneDesc(2, 'demo2', 'Mid 2001: Dragon Rock (T)', SFADEMO_GAME_INFO),
    new Early1MapSceneDesc(52, 'demo52', 'Mid 2001: Dragon Rock Bottom', SFADEMO_GAME_INFO),
    new Early1MapSceneDesc(48, 'demo48', 'Mid 2001: Boss T-rex', SFADEMO_GAME_INFO),
    new Early1MapSceneDesc(16, 'demo16', 'Mid 2001: CloudRunner Dungeon (T)', SFADEMO_GAME_INFO),
    new Early1MapSceneDesc(43, 'demo43', 'Mid 2001: CloudRunner Race (T)', SFADEMO_GAME_INFO),
    new Early1MapSceneDesc(12, 'demo12', 'Mid 2001: CloudRunner Fortress', SFADEMO_GAME_INFO),
    new Early1MapSceneDesc(30, 'demo30', 'Mid 2001: Inside CRF Galleon (T)', SFADEMO_GAME_INFO),
    new Early1MapSceneDesc(15, 'demo15', 'Mid 2001: CloudRunner Treasure Vault (T)', SFADEMO_GAME_INFO),
    new Early1MapSceneDesc(4, 'demo4', 'Mid 2001: Volcano Force Point Temple (T)', SFADEMO_GAME_INFO),
    new Early1MapSceneDesc(50, 'demo50', 'Mid 2001: Ocean Force Point - Top (T)', SFADEMO_GAME_INFO),
    new Early1MapSceneDesc(21, 'demo21', 'Mid 2001: Ocean Force Point Temple Bottom (T)', SFADEMO_GAME_INFO),
    new Early1MapSceneDesc(23, 'demo23', 'Mid 2001: Ice Mountain', SFADEMO_GAME_INFO),
    new Early1MapSceneDesc(10, 'demo10', 'Mid 2001: Snowhorn Wastes (T)', SFADEMO_GAME_INFO),
    new Early1MapSceneDesc(11, 'demo11', 'Mid 2001: Krazoa Palace (T)', SFADEMO_GAME_INFO),
    new Early1MapSceneDesc(13, 'demo13', 'Mid 2001: Walled City (T)', SFADEMO_GAME_INFO),
    new Early1MapSceneDesc(19, 'demo19', 'Mid 2001: DarkIce Mines (T)', SFADEMO_GAME_INFO),
    new Early1MapSceneDesc(27, 'demo27', 'Mid 2001: DarkIce Mines 2', SFADEMO_GAME_INFO),
    new Early1MapSceneDesc(28, 'demo28', 'Mid 2001: BOSS Galdon (T)', SFADEMO_GAME_INFO),
    new Early1MapSceneDesc(31, 'demo31', 'Mid 2001: Test of Combat', SFADEMO_GAME_INFO),
    new EarlydupMapSceneDesc(32, 'demo32', 'Mid 2001: Test of Fear (T)', SFADEMO_GAME_INFO),
    new Early1MapSceneDesc(33, 'demo33', 'Mid 2001: Test of Observation (T)', SFADEMO_GAME_INFO),
    new EarlydupMapSceneDesc(34, 'demo34', 'Mid 2001: Test of Knowledge (T)', SFADEMO_GAME_INFO),
    new EarlydupMapSceneDesc(39, 'demo31', 'Mid 2001: Test of Strength (T)', SFADEMO_GAME_INFO),
    new Early1MapSceneDesc(40, 'demo41', 'Mid 2001: Test of Sacrifice (T)', SFADEMO_GAME_INFO),
    new Early1MapSceneDesc(58, 'demo58', 'Mid 2001: Arwing to Planet', SFADEMO_GAME_INFO),
    new Early1MapSceneDesc(59, 'demo59', 'Mid 2001: Arwing to Darkice', SFADEMO_GAME_INFO),
    new Early2MapSceneDesc(60, 'demo60', 'Mid 2001: Arwing to Cloudrunner Fortress', SFADEMO_GAME_INFO),
    new Early1MapSceneDesc(61, 'demo61', 'Mid 2001: Arwing to Walled City', SFADEMO_GAME_INFO),
    new Early2MapSceneDesc(62, 'demo62', 'Mid 2001: Arwing to Dragon Rock', SFADEMO_GAME_INFO),
    new Early1MapSceneDesc(44, 'demo62', 'Mid 2001: Boss Drakor', SFADEMO_GAME_INFO),
    new Early1MapSceneDesc(38, 'demo62', 'Mid 2001: Andross', SFADEMO_GAME_INFO),
    
    'Mid-late 2001 Maps',
    new Early2MapSceneDesc(29, 'demo29', 'Mid-Late 2001: Cape Claw', SFADEMO_GAME_INFO),
    new Early2MapSceneDesc(14, 'demo14', 'Mid-Late 2001: LightFoot Village', SFADEMO_GAME_INFO),
    new Early2MapSceneDesc(2, 'demo2', 'Mid-Late 2001: Dragon Rock (T)', SFADEMO_GAME_INFO),
    new Early2MapSceneDesc(52, 'demo52', 'Mid-Late 2001: Dragon Rock Bottom', SFADEMO_GAME_INFO),
    new Early2MapSceneDesc(48, 'demo48', 'Mid-Late 2001 Boss T-rex (T)', SFADEMO_GAME_INFO),
    new Early2MapSceneDesc(16, 'demo16', 'Mid-Late 2001: CloudRunner Dungeon (T)', SFADEMO_GAME_INFO),
    new Early2MapSceneDesc(43, 'demo43', 'Mid-Late 2001: CloudRunner Race', SFADEMO_GAME_INFO),
    new Early2MapSceneDesc(12, 'demo12', 'Mid-Late 2001: CloudRunner Fortress (T)', SFADEMO_GAME_INFO),
    new Early2MapSceneDesc(4, 'demo4', 'Mid-Late 2001: Volcano Force Point Temple (T)', SFADEMO_GAME_INFO),    


    'Late 2001 Maps' ,
    new Early3MapSceneDesc(0, 'demo8', 'Late 2001: Ship Battle', SFADEMO_GAME_INFO),
    new Early3MapSceneDesc(65, 'demo63', 'Late 2001: Great Fox (T)', SFADEMO_GAME_INFO),
    new Early3MapSceneDesc(51, 'demo51', 'Late 2001: Shop (T)', SFADEMO_GAME_INFO),
    new Early3MapSceneDesc(33, 'demo33', 'Late 2001: Test of Observation (T)', SFADEMO_GAME_INFO),
    new Early3MapSceneDesc(11, 'demo11', 'Late 2001: Krazoa Palace (T)', SFADEMO_GAME_INFO),
    new Early3MapSceneDesc(19, 'demo19', 'Late 2001: DarkIce Mines (T)', SFADEMO_GAME_INFO),
    new Early3MapSceneDesc(27, 'demo27', 'Late 2001: DarkIce Mines 2 (T)', SFADEMO_GAME_INFO),
    new Early3MapSceneDesc(28, 'demo28', 'Late 2001: BOSS Galdon (T)', SFADEMO_GAME_INFO),
    new Early3MapSceneDesc(23, 'demo23', 'Late 2001: Ice Mountain (T)', SFADEMO_GAME_INFO),
    new Early3MapSceneDesc(66, 'demo67', 'Late 2001: LinkA (Warpstone Warp) (T)', SFADEMO_GAME_INFO),
    new Early3MapSceneDesc(56, 'demo56', 'Late 2001: LinkB (Ice2Wastes) (T)', SFADEMO_GAME_INFO),
    new Early3MapSceneDesc(67, 'demo68', 'Late 2001: LinkC (Wastes2Hollow) (T)', SFADEMO_GAME_INFO),
    new Early3MapSceneDesc(68, 'demo69', 'Late 2001: LinkD (DIM top 2 Bottom) (T)', SFADEMO_GAME_INFO),
    new Early3MapSceneDesc(54, 'demo54', 'Late 2001: Magic Cave (T)', SFADEMO_GAME_INFO),
    new Early3MapSceneDesc(10, 'demo10', 'Late 2001: Snowhorn Wastes (T)', SFADEMO_GAME_INFO),
    new Early3MapSceneDesc(7, 'demo7', 'Late 2001: ThornTail Hollow (T)', SFADEMO_GAME_INFO),
    new Early3MapSceneDesc(8, 'demo8', 'Late 2001: ThornTail Hollow Underground (T)', SFADEMO_GAME_INFO),


    'Early 2002 (Lzo Maps)',
    new Early4MapSceneDesc(51, 'demo51', 'Early 2002: Shop (T)', SFADEMO_GAME_INFO),
    new Early4MapSceneDesc(13, 'demo13', 'Early 2002: Walled City (T)', SFADEMO_GAME_INFO),
    new Early4MapSceneDesc(10, 'demo10', 'Early 2002: Snowhorn Wastes (T)', SFADEMO_GAME_INFO),
    new Early4MapSceneDesc(7, 'demo7', 'Early 2002: ThornTail Hollow (T)', SFADEMO_GAME_INFO),
    new Early4MapSceneDesc(8, 'demo8', 'Early 2002: ThornTail Well (T)', SFADEMO_GAME_INFO),
    new Early4MapSceneDesc(11, 'demo11', 'Early 2002: Krazoa Palace (T)', SFADEMO_GAME_INFO),
    new Early4MapSceneDesc(54, 'demo54', 'Early 2002: Magic Cave (T)', SFADEMO_GAME_INFO),
    new Early4MapSceneDesc(2, 'demo2', 'Early 2002: Dragon Rock', SFADEMO_GAME_INFO),
    new Early4MapSceneDesc(56, 'demo56', 'Early 2002: LinkB (Ice2Wastes) (T)', SFADEMO_GAME_INFO),
    new Early4MapSceneDesc(67, 'demo68', 'Early 2002: LinkC (Wastes2Hollow) (T)', SFADEMO_GAME_INFO),
    new Early4MapSceneDesc(68, 'demo69', 'Early 2002: LinkD (DIM top 2 Bottom) (T)', SFADEMO_GAME_INFO),
    new Early4MapSceneDesc(48, 'demo48', 'Early 2002: Boss T-rex (T)', SFADEMO_GAME_INFO),
    new Early4MapSceneDesc(33, 'demo33', 'Early 2002: Test of Observation (T)', SFADEMO_GAME_INFO),
    new Early4MapSceneDesc(19, 'demo19', 'Early 2002: DarkIce Mines (T)', SFADEMO_GAME_INFO),
    new Early4MapSceneDesc(27, 'demo27', 'Early 2002: DarkIce Mines 2 (T)', SFADEMO_GAME_INFO),
    new Early4MapSceneDesc(28, 'demo28', 'Early 2002: BOSS Galdon (T)', SFADEMO_GAME_INFO),
    new Early4MapSceneDesc(23, 'demo23', 'Early 2002: Ice Mountain (T)', SFADEMO_GAME_INFO),
    new Early4MapSceneDesc(14, 'demo14', 'Early 2002: LightFoot Village (T)', SFADEMO_GAME_INFO),
    new Early4MapSceneDesc(12, 'demo12', 'Early 2002: CloudRunner Fortress (T)', SFADEMO_GAME_INFO),
    new Early4MapSceneDesc(63, 'demo63', 'Early 2002: Title Screen (T)', SFADEMO_GAME_INFO),
    new Early4MapSceneDesc(59, 'demo59', 'Early 2002: Arwing to Darkice', SFADEMO_GAME_INFO),


    'Kiosk Maps',
     new SFAWorldSceneDesc("animtest", 'animtest', 26, 'Kiosk: Animtest', SFADEMO_GAME_INFO),
    new SFAMapSceneDesc(63, 'demo63', 'Kiosk: Great Fox', SFADEMO_GAME_INFO),
     new SFAWorldSceneDesc("clouddungeon", 'clouddungeon', 16, 'Kiosk: Cloudrunner Dungeon', SFADEMO_GAME_INFO),
    new SFAWorldSceneDesc('snowmines', 'darkicemines', 19, 'Kiosk: DarkIce Mines ', SFADEMO_GAME_INFO),
    new SFAWorldSceneDesc('snowmines2', 'darkicemines2', 27, 'Kiosk: DarkIce Mines 2 ', SFADEMO_GAME_INFO),
     new SFAWorldSceneDesc("newicemount", 'icemountain', 23, 'Kiosk: Ice Mountain Race', SFADEMO_GAME_INFO),
     new SFAWorldSceneDesc("snowmines3", 'bossgaldon', 28, 'Kiosk: BOSS Galdon', SFADEMO_GAME_INFO),
     new SFAMapSceneDesc(31, 'demo31', 'Kiosk: Test of Combat', SFADEMO_GAME_INFO,),
     new SFAWorldSceneDesc("mmshrine", 'mmshrine', 32, 'Kiosk: Test of Fear', SFADEMO_GAME_INFO),
     new SFAWorldSceneDesc( 'ecshrine', 'ecshrine', 33,'Kiosk: Test of Observation', SFADEMO_GAME_INFO),
     new SFAWorldSceneDesc("gpshrine", 'gpshrine', 34, 'Kiosk: Test of Knowledge', SFADEMO_GAME_INFO),
    new SFAWorldSceneDesc('dbshrine', 'dbshrine', 39, 'Kiosk: Test of Strength', SFADEMO_GAME_INFO),
     new SFAWorldSceneDesc("nwshrine", 'nwshrine', 40, 'Kiosk: NWshrine - Boss Scales', SFADEMO_GAME_INFO),
     new SFAMapSceneDesc(38, 'demo38', 'Kiosk: Arwing Arena', SFADEMO_GAME_INFO),
     new SFAWorldSceneDesc("cloudrace", 'cloudrace', 43, 'Kiosk: Cloudrunner Race', SFADEMO_GAME_INFO),
    // new SFAMapSceneDesc(45, 'demo45', 'Early Ice Mountain Arena', SFADEMO_GAME_INFO),
    // new SFAMapDesc(46, 'demo46', 'Location', SFADEMO_GAME_INFO, false),
    // new SFAMapDesc(47, 'demo47', 'Location', SFADEMO_GAME_INFO, false),
     new SFAWorldSceneDesc('trexboss', 'bosstrex', 48, 'Kiosk: Boss T-rex', SFADEMO_GAME_INFO),
    // new SFAMapDesc(49, 'demo49', 'Location', SFADEMO_GAME_INFO, false),
         new SFAWorldSceneDesc("finalboss", 'bossdrakor', 44, 'Kiosk: Boss Drakor', SFADEMO_GAME_INFO),
        new SFAWorldSceneDesc("swapcircle", 'lightfoot', 14, 'Kiosk: LightFoot Village', SFADEMO_GAME_INFO),
    new SFAWorldSceneDesc("mazecave", 'mazecave', 9, 'Kiosk: Maze Cave', SFADEMO_GAME_INFO,),
    new SFAWorldSceneDesc("hollow", 'swaphol', 7, 'Kiosk: ThornTail Hollow', SFADEMO_GAME_INFO),
            new SFAWorldSceneDesc("hollow2", 'swapholbot', 8, 'Kiosk: ThornTail Hollow Well', SFADEMO_GAME_INFO),
         new SFAWorldSceneDesc("moonpass", 'mmpass', 18, 'Kiosk: Moon Mountain Pass', SFADEMO_GAME_INFO),
         new SFAWorldSceneDesc("wastes", 'nwastes', 10, 'Kiosk: Snowhorn Wastes', SFADEMO_GAME_INFO),
        new SFAWorldSceneDesc( "temple",'volcano', 4, 'Kiosk: Volcano Force Point Temple', SFADEMO_GAME_INFO),
    new SFAWorldSceneDesc("capeclaw",'capeclaw', 29,'Kiosk: Cape Claw', SFADEMO_GAME_INFO),
        new SFAWorldSceneDesc("warlock", 'warlock', 11, 'Kiosk: Krazoa Palace', SFADEMO_GAME_INFO),
         new SFAWorldSceneDesc( 'wallcity','wallcity', 13, 'Kiosk: Walled City', SFADEMO_GAME_INFO),
     new SFAWorldSceneDesc("dfptop", 'dfptop', 50, 'Kiosk: Ocean Force Point Temple Exterior', SFADEMO_GAME_INFO),
         new SFAWorldSceneDesc( "kraztest", 'desert', 21,'Kiosk: Ocean Force Point Temple Interior', SFADEMO_GAME_INFO),
     new SFAWorldSceneDesc('swapstore', 'shop', 51, "kiosk: Shop", SFADEMO_GAME_INFO),
     new SFAWorldSceneDesc('dragrock', "dragrock" , 2, 'Kiosk: Dragon Rock', SFADEMO_GAME_INFO),
new SFAWorldSceneDesc('dragbot', 'dragrockbot', 52, 'Kiosk: Dragon Rock Bot', SFADEMO_GAME_INFO),
       new SFAWorldSceneDesc( 'fortress', "crfort", 12, 'Kiosk: CloudRunner Fortress', SFADEMO_GAME_INFO),

     new SFAWorldSceneDesc('magicave', 'magiccave', 54, 'Kiosk: Magic Cave', SFADEMO_GAME_INFO),
     new SFAMapSceneDesc(55, 'demo55', 'Kiosk: Ice Mountain Link', SFADEMO_GAME_INFO),
     new SFAMapSceneDesc(58, 'demo58', 'Kiosk: Arwing to Planet', SFADEMO_GAME_INFO),
     new SFAMapSceneDesc(59, 'demo59', 'Kiosk: Arwing to Darkice', SFADEMO_GAME_INFO),
     new SFAMapSceneDesc(60, 'demo60', 'Kiosk: Arwing to CRF', SFADEMO_GAME_INFO),
     new SFAMapSceneDesc(61, 'demo61', 'Kisok: Arwing to Walled City', SFADEMO_GAME_INFO),
     new SFAWorldSceneDesc('arwingdragon', 'arwingdragon', 62, 'Kiosk: Arwing to Dragon Rock', SFADEMO_GAME_INFO),
     new SFAMapSceneDesc(63, 'demo64', 'Kiosk: Title Screen', SFADEMO_GAME_INFO),
    new SFAMapSceneDesc(65, 'demo65', 'Kiosk Great Fox 2', SFADEMO_GAME_INFO),
    new SFAWorldSceneDesc( 'linka', "linka", 66, 'Kiosk: LinkA - Warpstone to others', SFADEMO_GAME_INFO),
       new SFAWorldSceneDesc( 'linkb', "linkb", 56, 'Kiosk: LinkB - Ice 2 Wastes', SFADEMO_GAME_INFO),
    new SFAWorldSceneDesc( 'linkc', "linkc", 67, 'Kiosk: LinkC - Wastes to Hollow', SFADEMO_GAME_INFO),
        new SFAWorldSceneDesc( 'linkd', "linkd", 68, 'Kiosk: LinkD - DIM to DIM 2', SFADEMO_GAME_INFO),
     new SFAMapSceneDesc(69, 'demo69', 'Kiosk: LinkE - hollow to moon pass', SFADEMO_GAME_INFO),
     new SFAMapSceneDesc(70, 'demo70', 'Kiosk: LinkF - moonpass to volcano', SFADEMO_GAME_INFO),
     new SFAMapSceneDesc(71, 'demo71', 'Kiosk: LinkG - hollow to lightfoot', SFADEMO_GAME_INFO),
     new SFAMapSceneDesc(72, 'demo72', 'Kiosk: LinkH - lightfoot to capecl', SFADEMO_GAME_INFO),
     new SFAWorldSceneDesc( 'linkj', "linkj", 73, 'Kiosk: LinkJ - Cape Claw 2 Ocean', SFADEMO_GAME_INFO),
     new SFAWorldSceneDesc( 'linki', "linki", 74, 'Kiosk: Linki -  CloudRunner2Race', SFADEMO_GAME_INFO),
 



    'Final Maps',
    new SFAWorldSceneDesc('gamefront', 'gamefront', 63, 'Great Fox'),
    new SFAWorldSceneDesc(['frontend', 'galleonship'], ['shipbattle', 'warlock'], null, 'Galleon'),
    new SFAWorldSceneDesc('warlock', 'warlock', 11, 'Krazoa Palace'),
    new SFAWorldSceneDesc('arwingtoplanet', 'arwingdarkice', 59, 'Arwing Flight (Main Planet)'),
    new SFAWorldSceneDesc('hollow', 'swaphol', 7, 'ThornTail Hollow'),
    new SFAWorldSceneDesc('swapstore', 'shop', 51, 'ThornTail Shop',),
    new SFAWorldSceneDesc('hollow2', ['swapholbot', 'swaphol'], 8, 'ThornTail Hollow Well'),
    new SFAWorldSceneDesc('magicave' /* sic */, 'magiccave', 54, 'Magic Cave'),
    new SFAWorldSceneDesc('mazecave', 'mazecave', 9, 'Cheat Token Maze'),
    new SFAWorldSceneDesc('moonpass', 'mmpass', 18, 'Moon Mountain Pass'),
    new SFAWorldSceneDesc('wastes', 'nwastes', 10, 'SnowHorn Wastes'),
    new SFAWorldSceneDesc('newicemount', 'icemountain', 23, 'Ice Mountain'),
    new SFAWorldSceneDesc('snowmines', 'darkicemines', 19, 'DarkIce Mines Exterior'),
    new SFAWorldSceneDesc('snowmines2', 'darkicemines2', 27, 'DarkIce Mines Interior'),
    new SFAWorldSceneDesc('capeclaw', 'capeclaw', 29, 'Cape Claw'),
    new SFAWorldSceneDesc('dfptop', 'dfptop', 50, 'Ocean Force Point Temple Exterior'),
    new SFAWorldSceneDesc('kraztest', 'dragrockbot', 21, 'Ocean Force Point Temple Interior'),
    new SFAWorldSceneDesc('swapcircle', 'lightfoot', 14, 'LightFoot Village'),
    new SFAWorldSceneDesc('fortress', 'crfort', 12, 'CloudRunner Fortress'),
    new SFAWorldSceneDesc('clouddungeon', 'clouddungeon', 16, 'CloudRunner Fortress Dungeon'),
    new SFAWorldSceneDesc('cloudrace', 'cloudrace', 43, 'CloudRunner Fortress Race'),
    new SFAWorldSceneDesc('wallcity', 'wallcity', 13, 'Walled City'),
    new SFAWorldSceneDesc('trexboss', ['bosstrex', 'wallcity'], 48, 'Walled City Boss (RedEye King)'),
    new SFAWorldSceneDesc('dragrock', 'dragrock', 2, 'Dragon Rock'),
    new SFAWorldSceneDesc('dragbot', 'dragrockbot', 52, 'Dragon Rock Bottom'),
    new SFAWorldSceneDesc('temple', 'volcano', 4, 'Volcano Force Point Temple'),
     new SFAWorldSceneDesc('bossdrakorflatr', 'bossdrakor', 44, 'Boss Drakor'),
    new SFAWorldSceneDesc('dfshrine', ['dfshrine', 'warlock' /* FIXME: needs another directory */], 31, 'Krazoa Shrine (Test of Combat)'),
    new SFAWorldSceneDesc('mmshrine', 'mmshrine', 32, 'Krazoa Shrine (Test of Fear)'),
    new SFAWorldSceneDesc('ecshrine', 'ecshrine', 33, 'Krazoa Shrine (Test of Observation)'),
    new SFAWorldSceneDesc('gpshrine', 'gpshrine', 34, 'Krazoa Shrine (Test of Knowledge)'),
    new SFAWorldSceneDesc('dbshrine', 'dbshrine', 39, 'Krazoa Shrine (Test of Strength)'),
    new SFAWorldSceneDesc('nwshrine', 'nwshrine', 40, 'Krazoa Shrine (Scales Encounter)'),
    // FIXME: which map is linka?
    new SFAWorldSceneDesc('linkb', 'linkb', 56, 'Ice Mountain Link 2'),
    new SFAWorldSceneDesc('linkc', 'linkc', 67, 'SnowHorn Wastes Link'),
    new SFAWorldSceneDesc('linkd', 'linkd', 68, 'DarkIce Mines Mineshaft'),
    new SFAWorldSceneDesc('linke', 'linke', 69, 'Moon Mountain Pass Link'),
    new SFAWorldSceneDesc('linkf', 'linkf', 70, 'Volcano Force Point Link'),
    new SFAWorldSceneDesc('linkg', 'linkg', 71, 'LightFoot Village Link'),
    new SFAWorldSceneDesc('linkh', 'linkh', 72, 'Cape Claw Link'),
    new SFAWorldSceneDesc('linkj', 'linkj', 73, 'Ocean Force Point Link'),
    new SFAWorldSceneDesc('linki', 'linki', 74, 'CloudRunner Fortress Link?'),
    new SFAWorldSceneDesc('animtest', 'animtest', 26, 'Test Map (animtest)'),
    new SFAWorldSceneDesc('animtest', 'bossgaldon', 28, 'Boss Galdon'),
    new SFAWorldSceneDesc('arwingdragon', 'arwingdragon', 62, 'Arwing to Dragon Rock', ),


    'MAPS BY DATE ORDER - Thorntail Hollow',
    new AncientMapSceneDesc('ancient3', "Ancient ThornTail Hollow (Textured)", ANCIENT_DP_GAME_INFO, 3),
    new Early1MapSceneDesc(7, 'demo7', 'Mid 2001: ThornTail Hollow', SFADEMO_GAME_INFO),
        new EarlydupMapSceneDesc(7, 'demo7', 'Mid 2001: ThornTail Hollow (Copy of Swaphol map)', SFADEMO_GAME_INFO),
    new Early3MapSceneDesc(7, 'demo7', 'Late 2001: ThornTail Hollow', SFADEMO_GAME_INFO),
    new Early4MapSceneDesc(7, 'demo7', 'Very Early 2002: ThornTail Hollow', SFADEMO_GAME_INFO),
    new SFAMapSceneDesc(7, 'demo7', 'Kiosk: ThornTail Hollow', SFADEMO_GAME_INFO),
    new SFAWorldSceneDesc('hollow', 'swaphol', 7, 'Final: ThornTail Hollow'),

    'Shop/Thorntail Store',
        new AncientMapSceneDesc('ancient6', "Ancient Shop (Textured)", ANCIENT_DP_GAME_INFO, 6),
    new Early1MapSceneDesc(51, 'demo51', 'Mid 2001: Shop', SFADEMO_GAME_INFO),
    new Early3MapSceneDesc(51, 'demo51', 'Late 2001: Shop', SFADEMO_GAME_INFO),
    new Early4MapSceneDesc(51, 'demo51', 'Early 2002: Shop', SFADEMO_GAME_INFO),
     new SFAWorldSceneDesc('swapstore', 'shop', 51, "kiosk: Shop", SFADEMO_GAME_INFO),
    new SFAWorldSceneDesc('swapstore', 'shop', 51, 'ThornTail Shop',),

];

const id = 'sfa';
const name = 'Star Fox Adventures';
export const sceneGroup: Viewer.SceneGroup = {
    id, name, sceneDescs,
};
